apiVersion: edictum/v1
kind: ContractBundle

metadata:
  name: customer-support-agent
  description: >
    Governance contracts for a customer support AI agent that handles
    ticket management, billing inquiries, refunds, and escalations.

defaults:
  mode: enforce

contracts:
  # --- ACCESS CONTROL --------------------------------------------------

  - id: billing-access-control
    type: pre
    tool: lookup_customer
    when:
      all:
        - args.include_billing: { equals: true }
        - principal.role: { not_in: [senior_agent, billing_specialist, supervisor] }
    then:
      effect: deny
      message: "Billing data access requires senior agent or billing specialist role."
      tags: [access-control, billing, pci-dss]

  - id: refund-limit
    type: pre
    tool: process_refund
    when:
      all:
        - args.amount: { gt: 500 }
        - principal.role: { not_in: [supervisor, billing_specialist] }
    then:
      effect: deny
      message: "Refunds over $500 require supervisor approval."
      tags: [access-control, financial, approval-required]

  # --- OPERATIONAL RULES -----------------------------------------------

  - id: escalation-requires-reason
    type: pre
    tool: escalate_ticket
    when:
      args.reason: { exists: false }
    then:
      effect: deny
      message: "Escalation requires a documented reason."
      tags: [process, escalation, documentation]

  - id: ticket-update-authorized-roles
    type: pre
    tool: update_ticket
    when:
      all:
        - args.status: { in: [closed, resolved] }
        - principal.role: { not_in: [senior_agent, supervisor] }
    then:
      effect: deny
      message: "Only senior agents and supervisors can close tickets."
      tags: [access-control, ticket-lifecycle]

  # --- OUTPUT GOVERNANCE -----------------------------------------------

  - id: pii-in-output
    type: post
    tool: "*"
    when:
      output.text:
        matches_any:
          - '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'         # Email
          - '\b(\+1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\b'         # US phone
          - '\b\d{1,5}\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*\s+(?:St|Ave|Rd|Blvd|Dr|Ln|Ct|Way|Pl)\b'  # Street address
          - '\*{4}\d{4}'                                                      # Partial credit card
    then:
      effect: warn
      message: "Potential PII detected in output. Review and redact before use."
      tags: [pii, gdpr, data-minimization]

  - id: pii-in-customer-lookup
    type: post
    tool: lookup_customer
    when:
      output.text:
        matches_any:
          - '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'         # Email
          - '\b(\+1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\b'         # US phone
          - '\b\d{1,5}\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*\s+(?:St|Ave|Rd|Blvd|Dr|Ln|Ct|Way|Pl)\b'  # Street address
          - '\*{4}\d{4}'                                                      # Partial credit card
          - '\b\d{3}-\d{2}-\d{4}\b'                                          # SSN
    then:
      effect: warn
      message: "PII detected in customer lookup output. Minimize data exposure."
      tags: [pii, customer-data]

  # --- OPERATIONAL LIMITS ----------------------------------------------

  - id: session-limits
    type: session
    limits:
      max_tool_calls: 20
      max_calls_per_tool:
        lookup_customer: 5
        process_refund: 3
        escalate_ticket: 2
    then:
      effect: deny
      message: "Session limit reached. Summarize findings and stop."
      tags: [rate-limit, operational-safety]
